model:
  renderer:
    class_path: internal.renderers.gsplat_v1_renderer.GSplatV1Renderer
    init_args:
      separate_sh: true
      tile_based_culling: true
  metric:
    class_path: internal.metrics.background_removal.BackgroundRemoval
    init_args:
      fused_ssim: true
  density:
    class_path: internal.density_controllers.background_removal.BackgroundRemoval
  renderer_output_types:
    - rgb
    - hard_inverse_depth
  random_background: true
