trainer:
  check_val_every_n_epoch: 10
model:
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  image_on_cpu: false